version: "3.4"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:10.3-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
    - published: ${DEMO_POSTGRES_PORT:-5432}
      target: 5432
    environment:
      POSTGRES_PASSWORD: 3x4mpl3

  #
  web:
    image: icalialabs/docker-lab-one:development
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: rails server
    ports:
    - published: ${DEMO_WEB_PORT:-3000}
      target: 3000
    volumes:
    - .:/usr/src
    entrypoint: /usr/src/bin/dev-entrypoint
    environment:
      DATABASE_URL: postgres://postgres:3x4mpl3@postgres:5432/demo_development
